const PROJECT_CONFIG = {
    BASE_SHEET_HEADER_ROWS: 1,
    SOURCE: {
        SHEET_ID: "1NVfMymJadfFuV5ROJB9ZamsCkXjM6hVRAz_Yku1ce_w",
        SHEET_NAME: "base",
        TERCEROS_SHEET_NAME: "terceros",
        APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbxE7bYU5u0ytSJsJ1sn_x7A4xLrsgKdmEEZiHoh9tpQ54z2Lthrlw2vhm9impe4WHVJ/exec",
    },
    DESTINATION: {
        SHEET_ID: "1U6AuWQgJY7SBMvbslRXVPRMe-VvrsaX23VgnfCmGL5I",
        SHEET_NAME: "datos",
        ROLLOS_SHEET_NAME: "rollos",
        APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbxLvIPjwJkUHJXTQnC99Um2RTSTZOMV7bjl7LyDg-kaRIsYgkcSkWhXh9_TcVifDUod1Q/exec",
    },
};

window.APP_CONFIG = {
    ...PROJECT_CONFIG,
    WEB_APP_URL: PROJECT_CONFIG.SOURCE.APPS_SCRIPT_URL,
    SOURCE_SHEET_ID: PROJECT_CONFIG.SOURCE.SHEET_ID,
    SOURCE_SHEET_NAME: PROJECT_CONFIG.SOURCE.SHEET_NAME,
    SOURCE_TERCEROS_SHEET_NAME: PROJECT_CONFIG.SOURCE.TERCEROS_SHEET_NAME,
    SOURCE_APPS_SCRIPT_URL: PROJECT_CONFIG.SOURCE.APPS_SCRIPT_URL,
    DESTINATION_SHEET_ID: PROJECT_CONFIG.DESTINATION.SHEET_ID,
    DESTINATION_SHEET_NAME: PROJECT_CONFIG.DESTINATION.SHEET_NAME,
    DESTINATION_APPS_SCRIPT_URL: PROJECT_CONFIG.DESTINATION.APPS_SCRIPT_URL,
};
